import { assertEquals, assertFalse, assertRejects, assertStringIncludes } from "@std/assert";

Deno.test("デスクトップアプリはChromiumを内蔵する", async () => {
  const config = JSON.parse(await Deno.readTextFile("deno.json"));
  assertEquals(config.desktop?.backend, "cef");
});

Deno.test("画面はViteでReactをバンドルして起動する", async () => {
  const config = JSON.parse(await Deno.readTextFile("deno.json"));
  const packageConfig = JSON.parse(await Deno.readTextFile("package.json"));
  const html = await Deno.readTextFile("index.html");
  const reactEntry = await Deno.readTextFile("desktop/ui.tsx");
  const reactApp = await Deno.readTextFile("desktop/ui/app.tsx");
  const errorBoundary = await Deno.readTextFile("desktop/ui/error-boundary.tsx");
  const dialogs = await Deno.readTextFile("desktop/ui/dialogs.tsx");
  const primitives = await Deno.readTextFile("desktop/ui/primitives.tsx");
  const sidebar = await Deno.readTextFile("desktop/ui/sidebar.tsx");
  const chatPane = await Deno.readTextFile("desktop/ui/chat.tsx");
  const appHook = await Deno.readTextFile("desktop/ui/hooks/use-kakomi-app.ts");
  const dashboardHook = await Deno.readTextFile("desktop/ui/hooks/use-dashboard.ts");
  const chatHook = await Deno.readTextFile("desktop/ui/hooks/use-chat.ts");
  const utilityPane = await Deno.readTextFile("desktop/ui/utility.tsx");
  const style = await Deno.readTextFile("desktop/style.css");
  const server = await Deno.readTextFile("server.ts");
  const viteConfig = await Deno.readTextFile("vite.config.ts");

  assertStringIncludes(packageConfig.dependencies.react, "19.2");
  assertStringIncludes(packageConfig.dependencies["react-dom"], "19.2");
  assertStringIncludes(packageConfig.dependencies["@base-ui/react"], "1.7");
  assertStringIncludes(packageConfig.dependencies.zustand, "5.0");
  assertStringIncludes(packageConfig.devDependencies.tailwindcss, "4.3");
  assertStringIncludes(packageConfig.devDependencies["@tailwindcss/vite"], "4.3");
  assertStringIncludes(packageConfig.devDependencies["happy-dom"], "20.11");
  assertStringIncludes(packageConfig.devDependencies.vite, "8.2");
  assertEquals(packageConfig.scripts.build, "vite build");
  assertEquals(config.tasks["ui:build"], "deno task build");
  assertStringIncludes(config.tasks.desktop, "deno desktop");
  assertStringIncludes(config.tasks.desktop, " .");
  assertEquals(config.compile.include, ["dist", "template"]);
  assertStringIncludes(config.tasks.desktop, "--allow-run");
  assertStringIncludes(viteConfig, 'publicDir: "node_modules/monaco-editor/min"');
  assertStringIncludes(viteConfig, 'outDir: "dist"');
  assertStringIncludes(viteConfig, 'from "@tailwindcss/vite"');
  assertStringIncludes(viteConfig, "tailwindcss()");
  assertStringIncludes(viteConfig, 'dedupe: ["react", "react-dom"]');
  assertStringIncludes(viteConfig, '"@base-ui/react/field"');
  assertStringIncludes(viteConfig, '"@base-ui/react/toggle-group"');
  assertStringIncludes(server, 'import "./desktop/app.ts"');
  assertStringIncludes(html, '<div id="root"></div>');
  assertStringIncludes(html, '<script type="module" src="/desktop/ui.tsx"');
  assertStringIncludes(html, 'content="__KAKOMI_API_TOKEN__"');
  assertStringIncludes(reactApp, 'from "./hooks/use-kakomi-app.ts"');
  assertStringIncludes(reactEntry, "<AppErrorBoundary>");
  assertStringIncludes(errorBoundary, "getDerivedStateFromError");
  assertStringIncludes(errorBoundary, 'role="alert"');
  assertStringIncludes(errorBoundary, "画面を再読み込み");
  assertStringIncludes(appHook, "useDashboard(");
  assertStringIncludes(appHook, "useChat(");
  assertStringIncludes(appHook, "useMatch(");
  assertStringIncludes(dialogs, 'from "@base-ui/react/dialog"');
  assertStringIncludes(dialogs, 'from "@base-ui/react/alert-dialog"');
  assertStringIncludes(dialogs, "<AlertDialog.Root");
  assertStringIncludes(primitives, 'from "@base-ui/react/tooltip"');
  assertStringIncludes(primitives, 'from "@base-ui/react/toggle"');
  assertStringIncludes(primitives, "export const Button");
  assertStringIncludes(primitives, "export function statusTone");
  assertStringIncludes(primitives, 'role={error ? "alert" : "status"}');
  assertStringIncludes(reactApp, "<Tooltip.Provider");
  assertStringIncludes(sidebar, "<TooltipButton");
  assertStringIncludes(sidebar, "aria-pressed={app.selected === version.path}");
  assertStringIncludes(chatPane, 'from "@base-ui/react/field"');
  assertStringIncludes(chatPane, 'from "@base-ui/react/toggle-group"');
  assertStringIncludes(chatPane, "<ToggleGroup");
  assertStringIncludes(chatPane, "<Field.Label");
  assertStringIncludes(chatPane, "<Field.Control");
  assertStringIncludes(chatPane, "<Field.Description");
  assertStringIncludes(chatPane, 'role="log"');
  assertStringIncludes(chatPane, 'aria-label="チャット履歴"');
  assertStringIncludes(utilityPane, 'from "@base-ui/react/tabs"');
  assertStringIncludes(utilityPane, "<Button");
  assertStringIncludes(style, '@import "tailwindcss/utilities.css"');
  assertStringIncludes(style, "grid-template-columns: 155px minmax(0, 1fr);");
  assertStringIncludes(style, ".sidebar-resize-handle {\n    display: none;\n  }");
  assertStringIncludes(style, ".resize-handle {\n    display: none;\n  }");
  assertFalse(style.includes(".match-button"));
  assertFalse(style.includes(".source-save-button"));
  assertFalse(dashboardHook.includes("prompt("));
  assertFalse(dashboardHook.includes("confirm("));
  assertFalse(chatHook.includes("confirm("));
  assertStringIncludes(
    await Deno.readTextFile("desktop/ui/hooks/use-app-state.ts"),
    'from "zustand/vanilla"',
  );
  await assertRejects(() => Deno.stat("desktop/ui_state.js"), Deno.errors.NotFound);
  assertFalse(html.includes("alpine"));
  assertFalse(html.includes("x-data"));
});
